export const API_AUTHENTICATION_ACTIONS = {
  START_FETCHING_TOKEN: 'START_FETCHING_TOKEN',
  FETCH_TOKEN_SUCCESS: 'FETCH_TOKEN_SUCCESS',
  FETCH_TOKEN_ERROR: 'FETCH_TOKEN_ERROR',
  RESET_BACKEND_AUTHENTICATION: 'RESET_BACKEND_AUTHENTICATION',
};
