export const REGISTRATION_ACTIONS = {
  RESET_FORM_VALUES: 'RESET_FORM_VALUES',
  SET_FORM_VALUES: 'SET_FORM_VALUES',
  ADD_CHILD: 'ADD_CHILD',
  DELETE_CHILD: 'DELETE_CHILD',
  SET_HOME_FORM_VALUES: 'SET_HOME_FORM_VALUES',
};
