export enum REGISTRATION_ACTIONS {
  SET_FORM_VALUES = 'SET_FORM_VALUES',
  RESET_FORM_VALUES = 'RESET_FORM_VALUES',
}

export enum VERIFY_STATUS {
  VERIFIED = 'VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
}
