export const EVENT_ACTIONS = {
  CLEAR_EVENT: 'CLEAR_EVENT',
  ENROL_CHILD: 'ENROL_CHILD',
  UNENROL_CHILD: 'UNENROL_CHILD',
  SAVE_CHILD_EVENTS: 'SAVE_CHILD_EVENTS',
  SAVE_CHILDREN_EVENTS: 'SAVE_CHILDREN_EVENTS',
};
